/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://nu6nqscxgrbxzdsdd4u3ebgzka.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-2vq5mzn7lbbgncjvas5fq4odpm",
  aws_cognito_identity_pool_id: "us-east-1:58e1bf9d-9c61-4027-955d-4776295224cc",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_tZvmtEQ14",
  aws_user_pools_web_client_id: "2d7m3c0qpmn1as1moke1u4jm7",
  oauth: {},
  // "aws_cognito_identity_pool_id": "us-east-1:10cff3ba-d322-4048-aa49-01bd7fd77c99",
  // "aws_cognito_region": "us-east-1",
  // "aws_user_pools_id": "us-east-1_xuc7kseKp",
  // "aws_user_pools_web_client_id": "4hb4ul8a3g6udia80sd56jvp2b",
  // "oauth": {}
}

export default awsmobile
