/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f6ae6d00-b69a-47ca-bf30-db7f8e273b1d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IfrnnzGFR",
    "aws_user_pools_web_client_id": "loki317mpnoh2kr57f6vaf85p",
    "oauth": {}
};


export default awsmobile;
